### ISSUE TITLE
Integrate into FE Decomp Portal

### ISSUE THREAD

**Issue by laqieer** [MokhaLeee/FireEmblem7J#1]
How about visualizing decomp progress in [FE Decomp Portal](https://laqieer.github.io/fe-decomp-portal/) like [FE6](https://github.com/StanHash/fe6) and [FE8](https://github.com/FireEmblemUniverse/fireemblem8u) decomp projects? I will take care of the UI change of the portal. Could you please upload progress data to [Frogress](https://github.com/decompals/frogress) like https://github.com/StanHash/fe6/issues/11 and https://github.com/FireEmblemUniverse/fireemblem8u/pull/307? Please let me know if I can be of assistance.

**Comment by MokhaLeee** [comment]
当然！如果可以的话，我非常乐意为此提供支持。不过或许是我没有尝试过 CI build 与 docker 的缘故，FE6 的 issue 中你提供的 giude 对我来说略微晦涩。如果可以的话，可以请你为这一部分的工作提供支持吗？这个仓库对大家都是完全开放的
